### ISSUE TITLE
broken GUI sample

### ISSUE THREAD

**Issue by eogloblin** [gnh1201/welsonjs#86]
Hi. I've found your project while looked for something for quick GUI prototyping for command line utils, but, unfortunately,  got an error from the start.
GUI sample looks like 
![image](https://github.com/gnh1201/welsonjs/assets/582939/d11504ca-1ccb-4f48-b0e2-6b2f27278d59)
Seems like your code is cutting 1st char from the app/index.html file while reading it at pipe-ipc.js:405 
Setting BOM for this file doesn't change anything, file still read without the first char.

**Comment by gnh1201** [comment]
Thank you for reporting the issue. I committed the fix to resolve this issue. Please feel free to let me know if the same problem occurs afterwards.

  * 9ff1f617b89a82fb90ea20b50229152d2062f1a6
  
Thank you. :)

**Comment by gnh1201** [comment]
Related issues: #84 #85
